/// Flutter icons CustomIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcons
///      fonts:
///       - asset: fonts/CustomIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'CustomIcons';
  static const _kFontPkg = null;

  static const IconData profile = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData history = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData info = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData qr_1 = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData contact = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData showpass_icon_ = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chat_sample_ = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData qr = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData email_sample_ = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData logout = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search_sample_ = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData edit_profile = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData history2 = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
